import type { RobotsSource } from "./robots.js";

export interface MerchantCollectionSource extends RobotsSource {
  collectionStatus:
    | "implemented"
    | "robots_allowed_needs_parser"
    | "blocked_for_generic_collector"
    | "needs_valid_robots"
    | "needs_source_confirmation";
  collectionNotes: string[];
}

export const MERCHANT_COLLECTION_SOURCES: MerchantCollectionSource[] = [
  {
    id: "olive-young",
    displayName: "Olive Young Global",
    baseUrl: "https://global.oliveyoung.com",
    samplePaths: ["/product/detail?prdtNo=GA210003128", "/display", "/product"],
    collectionStatus: "implemented",
    notes: ["Current implementation can use the public product sitemap/detail-data path or the existing local olive-poc dataset as fallback."],
    collectionNotes: [
      "Default target is 500 products via MERCHANT_TARGET_COUNT/OLIVE_TARGET_COUNT.",
      "OLIVE_SOURCE_MODE=auto uses public collection when the local PoC dataset has fewer than the target count.",
      "Local fallback uses C:/Users/SDS/workspace/olive-poc/data/catalog100-3.31/master_products.json.",
    ],
  },
  {
    id: "lotte-home-shopping",
    displayName: "Lotte Home Shopping",
    baseUrl: "https://www.lotteimall.com",
    samplePaths: ["/", "/recommendation/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt blocks User-agent * at root; do not crawl without partner permission or an allowed feed/API."],
  },
  {
    id: "lotte-wellfood",
    displayName: "Lotte Wellfood",
    baseUrl: "https://www.lottewellfood.com",
    samplePaths: ["/"],
    collectionStatus: "needs_valid_robots",
    collectionNotes: ["robots.txt was not available during audit; collect only after a valid product source and policy are confirmed."],
  },
  {
    id: "lotte-on",
    displayName: "LotteON",
    baseUrl: "https://www.lotteon.com",
    samplePaths: ["/p/product/", "/m/product/", "/csearch/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt allows product paths for specific named bots, but User-agent * is disallowed."],
  },
  {
    id: "lotte-himart",
    displayName: "Lotte Hi-Mart",
    baseUrl: "https://www.e-himart.co.kr",
    samplePaths: ["/", "/llms.txt", "/app/goods/goodsDetail?goodsNo=0000004539"],
    collectionStatus: "implemented",
    collectionNotes: [
      "robots.txt allows User-agent *.",
      "Uses sitemap product URLs and Schema.org Product JSON-LD from product detail pages.",
      "Default target is 500 products via MERCHANT_TARGET_COUNT/HIMART_TARGET_COUNT.",
    ],
  },
  {
    id: "kurly",
    displayName: "Kurly",
    baseUrl: "https://www.kurly.com",
    samplePaths: ["/", "/sitemap/index-sitemap.xml", "/goods/1001345818"],
    collectionStatus: "implemented",
    collectionNotes: [
      "robots.txt allows User-agent * for public product pages and disallows account/order/private paths.",
      "Uses public goods sitemaps and Schema.org Product JSON-LD on product detail pages.",
      "Default target is 500 products via MERCHANT_TARGET_COUNT/KURLY_TARGET_COUNT.",
    ],
  },
  {
    id: "stylekorean",
    displayName: "StyleKorean",
    baseUrl: "https://www.stylekorean.com",
    samplePaths: ["/", "/sitemap-products-1.xml", "/product/holika-holika-pig-clear-black-head-3-step-kit-1-sheet/1093"],
    collectionStatus: "implemented",
    collectionNotes: [
      "robots.txt allows public catalog/product access while blocking admin/plugin paths.",
      "Uses product sitemap and Schema.org Product JSON-LD on product detail pages.",
      "Default target is 500 products via MERCHANT_TARGET_COUNT/STYLEKOREAN_TARGET_COUNT.",
    ],
  },
  {
    id: "coupang",
    displayName: "Coupang",
    baseUrl: "https://www.coupang.com",
    samplePaths: ["/robots.txt", "/sitemap.xml"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt, sitemap, and product JSON probes returned HTTP 403 to the generic collector; use official partner API/feed only."],
  },
  {
    id: "naver-shopping",
    displayName: "Naver Shopping",
    baseUrl: "https://shopping.naver.com",
    samplePaths: ["/", "/robots.txt"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root; do not collect via generic crawler."],
  },
  {
    id: "gmarket",
    displayName: "Gmarket",
    baseUrl: "https://www.gmarket.co.kr",
    samplePaths: ["/robots.txt", "/sitemap.xml"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt and sitemap probes returned HTTP 403 to the generic collector; use approved API/feed."],
  },
  {
    id: "auction",
    displayName: "Auction",
    baseUrl: "https://www.auction.co.kr",
    samplePaths: ["/robots.txt", "/sitemap.xml"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt and sitemap probes returned HTTP 403 to the generic collector; use approved API/feed."],
  },
  {
    id: "11st",
    displayName: "11st",
    baseUrl: "https://www.11st.co.kr",
    samplePaths: ["/", "/robots.txt"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root; do not collect via generic crawler."],
  },
  {
    id: "ssg",
    displayName: "SSG.COM",
    baseUrl: "https://www.ssg.com",
    samplePaths: ["/", "/item/itemView.ssg"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root during audit; use partner feed/API for Shinsegae/SSG product data."],
  },
  {
    id: "gsshop",
    displayName: "GS Shop",
    baseUrl: "https://www.gsshop.com",
    samplePaths: ["/", "/shop/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root during audit; use partner feed/API."],
  },
  {
    id: "hyundai-hmall",
    displayName: "Hyundai Hmall",
    baseUrl: "https://www.hmall.com",
    samplePaths: ["/", "/p/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root during audit; use partner feed/API."],
  },
  {
    id: "zigzag",
    displayName: "Zigzag",
    baseUrl: "https://zigzag.kr",
    samplePaths: ["/", "/sitemap.xml"],
    collectionStatus: "needs_source_confirmation",
    collectionNotes: ["robots.txt allows public paths, but no product-level sitemap/feed was confirmed in the quick audit."],
  },
  {
    id: "ably",
    displayName: "Ably",
    baseUrl: "https://m.a-bly.com",
    samplePaths: ["/", "/robots.txt"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots/source probes returned HTTP 403 to the generic collector; use approved API/feed."],
  },
  {
    id: "29cm",
    displayName: "29CM",
    baseUrl: "https://www.29cm.co.kr",
    samplePaths: ["/", "/sitemap.xml"],
    collectionStatus: "needs_source_confirmation",
    collectionNotes: ["robots.txt allows public paths, but a product-level sitemap/feed was not confirmed in the quick audit."],
  },
  {
    id: "wconcept",
    displayName: "W Concept",
    baseUrl: "https://www.wconcept.co.kr",
    samplePaths: ["/", "/Product/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt disallows User-agent * at root during audit; use partner feed/API."],
  },
  {
    id: "kream",
    displayName: "KREAM",
    baseUrl: "https://kream.co.kr",
    samplePaths: ["/", "/products/"],
    collectionStatus: "needs_valid_robots",
    collectionNotes: ["robots/source probe did not return a stable valid robots response during audit; confirm an approved source before collection."],
  },
  {
    id: "danawa",
    displayName: "Danawa",
    baseUrl: "https://www.danawa.com",
    samplePaths: ["/", "/sitemap.xml"],
    collectionStatus: "needs_source_confirmation",
    collectionNotes: ["robots.txt allows some public access, but no product-level sitemap/feed was confirmed in the quick audit."],
  },
  {
    id: "sulwhasoo-us",
    displayName: "Sulwhasoo US",
    baseUrl: "https://us.sulwhasoo.com",
    samplePaths: ["/products.json?limit=1", "/.well-known/ucp", "/products/summer-ritual-bundle"],
    collectionStatus: "implemented",
    collectionNotes: [
      "Shopify storefront allows public product catalog access.",
      "UCP/MCP discovery is available for future agentic commerce integration.",
      "Uses /products.json for product-level public catalog collection.",
    ],
  },
  {
    id: "innisfree-jp",
    displayName: "Innisfree JP",
    baseUrl: "https://www.innisfree.jp",
    samplePaths: ["/products.json?limit=1", "/.well-known/ucp", "/products/gtmilk-duo-set-asse"],
    collectionStatus: "implemented",
    collectionNotes: [
      "Shopify storefront allows public product catalog access.",
      "UCP/MCP discovery is available for future agentic commerce integration.",
      "Uses /products.json for product-level public catalog collection.",
    ],
  },
  {
    id: "yogiyo",
    displayName: "Yogiyo",
    baseUrl: "https://www.yogiyo.co.kr",
    samplePaths: ["/", "/api/"],
    collectionStatus: "needs_source_confirmation",
    collectionNotes: ["robots.txt disallows /api/ and payment/admin paths; collection needs a public, non-location-sensitive product/menu source or partner access."],
  },
  {
    id: "lotte-chilsung",
    displayName: "Lotte Chilsung Mall",
    baseUrl: "https://www.lottechilsungmall.com",
    samplePaths: ["/"],
    collectionStatus: "needs_valid_robots",
    collectionNotes: ["Candidate mall domain did not resolve during audit; confirm official product URL before collection."],
  },
  {
    id: "musinsa",
    displayName: "Musinsa",
    baseUrl: "https://www.musinsa.com",
    samplePaths: ["/products/", "/auth/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt blocks User-agent * and grants access only to named bots/groups; do not use the generic collector."],
  },
  {
    id: "cj-onstyle",
    displayName: "CJ OnStyle",
    baseUrl: "https://www.cjonstyle.com",
    samplePaths: ["/"],
    collectionStatus: "needs_valid_robots",
    collectionNotes: ["robots.txt request returned HTML during audit, so policy is ambiguous until a valid robots endpoint/source is confirmed."],
  },
  {
    id: "lfmall",
    displayName: "LFmall",
    baseUrl: "https://www.lfmall.co.kr",
    samplePaths: ["/"],
    collectionStatus: "blocked_for_generic_collector",
    collectionNotes: ["robots.txt blocks User-agent *; only named bots are allowed."],
  },
];
